### ISSUE TITLE
Proposal: Add address as top level field in project level schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/infrastructure#12]
In the alpha project level schema, `address` is added to the `location` object .

**Proposal:**

For consistency with the OCDS location extension, add `address` as a top level field in the project level schema instead.

**Comment by jpmckinney** [comment]
For additional context, the description of the field is: "A physical address where works will take place"

https://github.com/open-contracting/infrastructure/blob/profile-draft/schema/project-level/project-schema.json#L579-L583

**Comment by timgdavies** [comment]
The reason for including address in `location` is that it is one of the ways to provide location, choosing between:

* Geometry
* Gazetteer
* Address

Whereas putting it at the top level would make the semantics of the address unclear, and leave the suggestion that publishers need to provide one of Geometry or Gazetteer in order to locate a project. 

I don't think there is a requirement to be consistent with the OCDS location extension here, outside avoiding arbitrary changes to things like how geometry or gazetteer entries are represented.

**Comment by jpmckinney** [comment]
I think it's fine for there to be an `address` field within a `Location` object. We presently only have `address` at `Organization.address`, so there isn't a deep precedent for where `address` fields go.
