### ISSUE TITLE
Discussion: Socioeconomic purpose

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/infrastructure#15]
CoST IDS has an element titled "Purpose" and in draft guidance note 9, this is described as:

> Specify the socio economic purpose of the project

Should we have a field for this in the project level data specification? If so, should it be free text, a document, or using some sort of codelist?

**Comment by jpmckinney** [comment]
For context, 'Purpose' is also in Guidance note 6 under 'Project Identification'.

**Comment by duncandewhurst** [comment]
From consultation at IODC:

* This element has been interpreted differently in different implementations (since guidance note 9 is unpublished)
* Ideally it should be a codelist (no specific classification was suggested) plus a free text field

**Comment by jpmckinney** [comment]
I just noticed that `additionalClassifications` refers to COFOG:

> One or more additional project classifications can be provided to described the social or economic focus of the project. This classification may take place against a locally developed codelist, or a globally established codelist such as UN COFOG (Classification of the Functions of Government)."

However, I expressed concerns in https://github.com/open-contracting/infrastructure/issues/16#issuecomment-424143570 about using COFOG for purposes (no pun intended) for which it wasn't designed. It doesn't seem like COFOG can describe the social or economic focus of a project. Can you provide an example about the appropriateness of COFOG?

**Comment by EvelynDinora** [comment]
I think it could be useful use a catalog based on the OECD purpose code list but will consult with other CoST team and come back on this.

**Comment by duncandewhurst** [comment]
For reference the OECD DAC/CRS codelists are available [here](http://www.oecd.org/dac/stats/dacandcrscodelists.htm) and the most recent version of the purpose codes are available in [this Excel file](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/DAC-CRS-CODES.xls).

Similarly to COFOG, the OECD purpose codes cover a much broader scope than infrastructure projects would cover, e.g. there are codes for "Participation in international peacekeeping operations", and "Communications policy and administrative management".

The OECD's description of the purpose codes states that they are

> used to identify the sector of destination of a contribution.

And IATI [considers them to be sector codes](http://reference.iatistandard.org/203/codelists/Sector/) so these codes may be more relevant to the discussion on project sector rather than socioeconomic purpose.

**Comment by duncandewhurst** [comment]
@jpmckinney I have removed the reference to COFOG from the `additionalClassification` description.

If we find an appropriate codelist we can update the description accordingly.

**Comment by Manu2510** [comment]
Hi everyone, I think the the purpose must be in a a free text box, as we don't have a proper CodeList that could be use in all the countries, maybe in the future we can develop a formal CodeList for Infrastructure projects.

**Comment by EvelynDinora** [comment]
As commented by Manuel we did a quick research in different CoST countries and agree that is better to have a free text to describe the purpose. In some countries there are not lists or catalogs and in others the catalog is not similar to others. This depends mainly on the general planning systems in every country and national strategic objectives.

**Comment by duncandewhurst** [comment]
Great, thanks @EvelynDinora
