### ISSUE TITLE
Test JSON files contain non-schema fields and codes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#172]
Fields:

* awardValue
* contractType
* projectPhase
* tenderValue

Codes:

* auditAndEvaluation

**Comment by duncandewhurst** [comment]
If you mean the files in `schema/tests`, I don't think these are used for anything, at least I can't find any reference to them elsewhere in the project.

I believe they were created by Tim for testing when he was working on the the alpha release and have since been superseded by the JSON file used in the worked example.

Unless you are using them somewhere, I will remove them.

**Comment by jpmckinney** [comment]
Yes, let's remove them then.
