### ISSUE TITLE
Implementation guidance: Linking to related information from transparency portals

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/infrastructure#18]
John Hawkins observed:

> What I find interesting about the Highways England website is they state when there will be traffic restrictions due to the work. My guess is that this is the information that is of most interest to people.

We should consider including implementation guidance that encourages the creators of transparency portals to consider the information that citizens will want, and to include this alongside more in-depth scrutiny-related information.

**Comment by jpmckinney** [comment]
The specific example seems more the scope of transport agencies, perhaps using http://www.open511.org – though guidance can certainly suggest linking to related information.

**Comment by jpmckinney** [comment]
The issue should perhaps be renamed, 'linking to related information from transparency portals', because 'focus on user needs' is overbroad (could mean too many things).

**Comment by duncandewhurst** [comment]
Since design of infrastructure transparency portals is outside the scope of the documentation, the most relevant place for this guidance seems to be in the [Publishing data from an infrastructure transparency portal](https://open-contracting.github.io/infrastructure/guidance/publishing-from-portal/) implementation guidance.

I have added an admonition to the draft guidance for this section as follows:

> **Linking to related information**
> Infrastructure transparency portal creators should consider what other types of information might be important to citizens, in addition to the in depth scrutiny related information in the project level data specification.
> 
> For example, [Highways England](https://highwaysengland.co.uk/roads/) provides links to congestion and traffic restriction information alongside information on roads projects.
