### ISSUE TITLE
documentType: new code to describe maintenance plan

### ISSUE THREAD

**Issue by odscjen** [open-contracting/infrastructure#470]
# Background

As part of CoST new sustainability modules a new data point in the Economic module is being created to disclose the maintenance plan

"Maintenance plan or program: A document that defines work done to prevent asset breakdowns and malfunctioning (ISO definition:[ Sample_Quality_Management_Manual-Process.pdf (9001simplified.com)](https://www.9001simplified.com/pdf/Sample_Quality_Management_Manual-Process.pdf)"

# Suggested OC4IDS Mapping:

Project Level:

[Add a project document](https://standard.open-contracting.org/infrastructure/latest/en/cost/common/#add-a-project-document) and set its [.documentType](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#project-schema.json,/definitions/Document,documentType) to 'maintenancePlan'.

# Proposal

Add the following codes:

Codelist | Code | Title | Description
-- | -- | -- | --
documentType | maintenancePlan | Maintenance plan | Documentation that defines work that will be done to prevent asset breakdowns and malfunctioning.

# Example

```json
{
  "documents": [
    {
      "id": "1",
      "title": "Maintenance plan or program",
      "documentType": "maintenancePlan",
      "url": "http://example.com/documents/maintenancePlanpdf"
    }
  ]
}
```

**Comment by odscjen** [comment]
@mgraca-prado could you confirm here the final wording of the IDS data point?

@jpmckinney any objections to us adding this code?

**Comment by mgraca-prado** [comment]
@odscjen. That is perfect. There is only a space after the word "malfunctioning" in case you would like to remove it.

**Comment by jpmckinney** [comment]
maintenance in projectsStatus "covers any preventative or corrective maintenance" and in costCategory is defined as "to retain an asset or its parts so that it can perform its required functions. Maintenance includes conducting corrective, responsive and preventative maintenance on an asset or its parts and all associated management, cleaning, services, repainting, repairing or replacing of parts as needed for the asset to be used for its intended purpose"

Obviously, a maintenance **plan** will only cover preventative, like in the proposed definition.

Maybe just a slight rewording:

> Documentation that describes work to prevent the breakdown or malfunctioning of an asset.

**Comment by odscjen** [comment]
Great thanks both, @jpmckinney your rewording looks good to me
