### ISSUE TITLE
Schema test errors

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/infrastructure#51]
I started working to restore the test that was commented out in Travis and fixed some errors already:

* Bad casing of `Code`, etc. in contractNature.csv
* Invalid JSON in the two test files
* Bad line endings in CSV files (`LFCR` or `CRLF` instead of `LF`)
* flake8 and whitespace

However, some issues require discussion:

* [x] 1. It's not specified whether contractingProcessStatus.csv or method.csv are open or closed codelists. I assume closed.
* [x] 2. We allow null in many fields, but this schema doesn't support merging. Therefore, I think we should remove null as an allowed value for all fields. I can do this via borrow-schema.py
* [x] 3. Should ID fields be required on objects in arrays? If so we're missing `Classification`, `Location`, `ContractingProcess`, `LinkedRelease`

Some missing properties:

* [x] /properties/budget/properties/amount/title
* [x] /properties/budget/properties/amount/description
* [x] /definitions/ContractingProcess/properties/summary/title
* [x] /definitions/ContractingProcess/properties/summary/description

I'll go with my assumptions in (1) in a PR, since I already started on those changes, but we can of course change the PR.

**Comment by jpmckinney** [comment]
PR is #52

**Comment by duncandewhurst** [comment]
Discussed with @jpmckinney:

2. is correct and will be included in alpha-2 - @jpmckinney will update the PR
3. will require more detailed review so we will wait until the beta release.

I'll address the missing properties

**Comment by duncandewhurst** [comment]
#52 is merged, moving this issue to the beta milestone

**Comment by duncandewhurst** [comment]
>     * [ ]  3. Should ID fields be required on objects in arrays? If so we're missing `Classification`, `Location`, `ContractingProcess`, `LinkedRelease`

I've reviewed whether these objects need required identifiers and propose the following:

* `ContractingProcess` -  we don't currently have an identifier on the contracting process object. We could make `contractingProcess/Summary/ocid` a required field, but that would which would require OC4IDS publishers to mint `ocid`'s when no OCDS data is available, and dealing with a nested identifier would have implications for tooling, in particular for conversion from spreadsheet to JSON format. Instead, I propose we add a required 'id' field on the parent object, which should be populated with the `ocid` when available otherwise a local identifier for the contracting process can be minted. We could then either remove the `ocid` field from the summary object, or leave it there but only have it used when an actual ocid exists (I prefer removing it).

* `Classification` - do not make `id` required, since it may not be unique (more than one classification scheme could share the same identifier), there are no children which would need to refer to `classification` as the parent in a flattened representation, and publishers can replace the whole `additionalClassifications` array if they need to change the classification of a project (equivalent to whole list merge in OCDS).

* `Location` - add an `id` field (a local identifier for this location) and make it required, since it seems likely that publishers may wish to update only one of the locations associated with a project (for example updating a line or polygon if the physical footprint of the project is extended but not updating the address or gazetteer entry for the project)

* `LinkedRelease` - make all fields required, including id, since now that `modifications` is a property of `contractingProcessSummary` rather than `linkedRelease`, this block is only used to reference OCDS releases and all fields are required in OCDS.

@jpmckinney please let me know your thoughts.

**Comment by jpmckinney** [comment]
Sounds good to me. Regarding `ocid`, what if no OCDS data is available, such that they mint an `id`, and then at a later date OCDS data becomes available? I think it's better for that scenario to have both an `id` and `ocid` field; the `id` stays the same, and the `ocid` gets filled in.

The guidance can still be that, if OCDS data is available, then both `id` and `ocid` should be the `ocid` from the OCDS data if available. This seems better, semantically, as the interpretation of `id` doesn't change dependent on the availability of OCDS data.

**Comment by duncandewhurst** [comment]
Thanks @jpmckinney I agree with your suggestion, the changes are staged in PR #105

**Comment by jpmckinney** [comment]
Noting that there are now some new schema test errors, for which I'll open a new issue.
